services:
  postgres:
    image: postgres:16-alpine
    container_name: talvra_postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-talvra}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-talvra}"
      POSTGRES_DB: "${POSTGRES_DB:-talvra}"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: talvra_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.30.0
    container_name: talvra_azurite
    command: ["azurite", "--blobHost", "0.0.0.0", "--location", "/data", "--debug", "/dev/null"]
    ports:
      - "${AZURITE_BLOB_PORT:-10000}:10000"
    volumes:
      - azuritedata:/data

  auth-service:
    build:
      context: ..
      dockerfile: services/auth-service/Dockerfile
    container_name: talvra_auth_service
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped
    ports:
      - "4001:4001"

  api-gateway:
    build:
      context: ..
      dockerfile: services/api-gateway/Dockerfile
    container_name: talvra_api_gateway
    env_file:
      - .env
    depends_on:
      auth-service:
        condition: service_started
    restart: unless-stopped
    ports:
      - "3001:3001"

  web:
    build:
      context: ..
      dockerfile: frontend/web/Dockerfile
    container_name: talvra_web
    env_file:
      - .env
    depends_on:
      api-gateway:
        condition: service_started
    ports:
      - "5173:5173"

  ingestion-service:
    build:
      context: ..
      dockerfile: services/ingestion-service/Dockerfile
    container_name: talvra_ingestion_service
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped
    ports:
      - "4010:4010"

  media-service:
    build:
      context: ..
      dockerfile: services/media-service/Dockerfile
    container_name: talvra_media_service
    env_file:
      - .env
    depends_on:
      api-gateway:
        condition: service_started
    restart: unless-stopped
    ports:
      - "4030:4030"

  ai-service:
    build:
      context: ..
      dockerfile: services/ai-service/Dockerfile
    container_name: talvra_ai_service
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      api-gateway:
        condition: service_started
    ports:
      - "4020:4020"
  canvas-service:
    build:
      context: ..
      dockerfile: services/canvas-service/Dockerfile
    container_name: talvra_canvas_service
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped
    ports:
      - "4002:4002"

volumes:
  pgdata:
  redisdata:
  azuritedata:
