# Example secrets manifest. Copy to secrets.yaml or secrets.local.yaml and fill with your real values.
# Never commit real secrets to git; this file is for reference only.
apiVersion: v1
kind: Secret
metadata:
  name: talvra-secrets
  namespace: talvra
type: Opaque
stringData:
  DATABASE_URL: "{{DATABASE_URL}}"
  REDIS_URL: "{{REDIS_URL}}"
  FRONTEND_ORIGIN: "{{FRONTEND_ORIGIN}}"
  AUTH_COOKIE_SECRET: "{{AUTH_COOKIE_SECRET}}"
  CANVAS_TOKEN_SECRET: "{{CANVAS_TOKEN_SECRET}}"
  GOOGLE_CLIENT_ID: "{{GOOGLE_CLIENT_ID}}"
  GOOGLE_CLIENT_SECRET: "{{GOOGLE_CLIENT_SECRET}}"
  GOOGLE_REDIRECT_URI: "{{GOOGLE_REDIRECT_URI}}"
  CANVAS_BASE_URL: "{{CANVAS_BASE_URL}}"
  AZURE_STORAGE_CONNECTION_STRING: "{{AZURE_STORAGE_CONNECTION_STRING}}"
  AZURE_STORAGE_CONTAINER: "{{AZURE_STORAGE_CONTAINER}}"
  OPENAI_CHAT_MODEL: "gpt-4o-mini"
  OPENAI_EMBED_MODEL: "text-embedding-3-small"
  AI_SERVICE_URL: "http://ai-service:4020"
  MEDIA_SERVICE_URL: "http://media-service:4030"
  AI_OUTPUT_DIR: "./services/ai-service/out"
  MEDIA_OUTPUT_DIR: "./services/media-service/out"

